---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[apt-repo]
      - recipe[atom]
      - recipe[td-agent-private]
    attributes:
      java:
        jdk_version: 7
